### ISSUE TITLE
11 years since last release

### ISSUE THREAD

**Issue by pangoSE** [splintchecker/splint#11] opened 2018-11-01 22:05 UTC
Maybe it is time for some of the 35 forkers to step up and prepare a release with a new maintainer?
Sergey seems to have quit github (0 activity during 2018)

**Comment by oxr463** [comment] 2018-12-12 19:38
@pangoSE, have you tried contacting him via email? Perhaps we can create a new GitHub Organization for the project.

**Comment by swedebugia** [comment] 2018-12-13 06:14
Done :)

**Comment by oxr463** [comment] 2018-12-13 12:18
@swedebugia do you have a link?

**Comment by damorinCan** [comment] 2018-12-13 13:10
Hi,

if that helps, one of the last thing that I've seen on splint mailing list (currently archive is down) was a patch for C11 support:

https://github.com/flpa/splint/commits/BA1

and another change here:

http://repo.or.cz/splint-patched.git

**Comment by swedebugia** [comment] 2018-12-13 14:06
@oxr463 link to what? the email I sent? its here:
"I would like to package splint for guix as it is needed in other projects.

Are you still maintaining this software?

If not could you archive it and clearly state that it needs a new maintainer?

Cheers

swedebugia"

**Comment by oxr463** [comment] 2018-12-13 14:12
@swedebugia oh, sorry. I thought you meant you forked it under a new organization.

I too send him an email asking if he was still interested in maintaining this project,
and asking his blessing to fork.

**Comment by ravenexp** [comment] 2018-12-13 19:22
Sorry for the late reply.

I must first disclaim any relationship to splint development.
All credit goes to splint authors: http://www.splint.org/credits.html

What I did is: 
1. convert the seemingly abandoned CVS repo from sourceforge to git.
2. write a few patches fixing the  most obvious build system and test bench problems.
3. ran out of disposable  time

People seem to think of this GitHub project as the current upstream, but this is not true.
The dead SF project is.
If there are any volunteers that wish to take over the github repo, I'd happily transfer the project ownership
(if I knew how to do it).

As it is, I've found splint code base pretty much unmaintainable, especially wrt. extending
the grammar to accept modern C dialects.
Even the C99 declaration support patch seemed to have some nasty side-effects.

I'd rather use clang static analyzer or one of the commercial lint tools myself.

**Comment by oxr463** [comment] 2018-12-14 19:58
@ravenexp perhaps you could archive this repository and/or put a link to this issue in the README so that people stop bothering you ;D

**Comment by bauen1** [comment] 2018-12-31 16:35
@ravenexp This might not be the official upstream, but it is linked as the official upstream from http://www.splint.org/ under `Source code:`
It it possible to transfer the entire repo to a GitHub organization or another person, see https://help.github.com/articles/about-repository-transfers/ and the `Further Reading` Section.

**Comment by ravenexp** [comment] 2019-01-01 18:53
> This might not be the official upstream, but it is linked as the official upstream from http://www.splint.org/ under Source code:

Eh, what? I'm not related to splint.org website  in any way and whoever is still maintaining it haven't sent me an email or contacted me otherwise. And here I was puzzled about why and how do people keep finding this repo after so many years of inactivity...

I'd rather transfer the repo to people who keep the official project website afloat. It looks like all I need is a github username to transfer to.

**Comment by evansuva** [comment] 2019-01-01 19:01
Sorry, I thought we did have a few emails many years ago, but I don't recall the details.

I'm not able to maintain splint these days and we haven't had any active development of it going on in my group for close to 20 years. The last repository we maintained was on sourceforge. 

If someone is interested in maintaining this and becoming the designated repository, I'm happy to update the link. Or, if no one volunteers for this and you just want to transfer ownership, you can transfer it to the https://github.com/splintchecker organization.

**Comment by bpringlemeir** [comment] 2019-07-19 20:16
The repo on sourceforge is obsolete as they don't support CVS access anymore.  I have write access and not admin access. However, I did an rsync to get there CVS server data and can use that locally.  However, this github project was the current best and I would be happy to have it here as opposed to source forge.  I think it is pointless to deal with them.  Also the dr. evans web sight points here.

I was working on a gcc plugin that might be backwards compatible.  Some contributions on this project are harmless and can be applied.  I was going with the fact that the regression tests passed and added the new features for c99 type stuff in the 2010 commits.

**Comment by bpringlemeir** [comment] 2019-07-19 20:19
Err, I can't modify the source forge stuff because it needs admin rights which only Dr. Evans has.  However I think github is fine and we would just end up with the same thing on source forge.. that is what I was trying to say.

**Comment by ravenexp** [comment] 2019-07-25 10:35
Sorry for being unresponsive for so long.

I've tried transferring the repository to https://github.com/splintchecker,
however I do not seem to have the required permissions within that organization.

As soon as this issue is fixed, I'll transfer the ownership, if no one objects.

**Comment by evansuva** [comment] 2019-07-25 12:40
You should have a github invite to splintchecker now, so I think you can create a new repository there.

**Comment by bpringlemeir** [comment] 2019-07-25 14:25
I haven''t seen this invite yet?  Sergey said that he was also having issues.  I cann't really find any cleardocumentation on how things are suppose to work at github.  Thanks for trying.  I am sure you havesome more important things to do.
   On Thursday, July 25, 2019, 8:40:15 a.m. EDT, David Evans <notifications@github.com> wrote:  
 
 
You should have a github invite to splintchecker now, so I think you can create a new repository there.

**Comment by bpringlemeir** [comment] 2019-07-25 17:46
This page seems to be helpful.
 https://help.github.com/en/articles/transferring-a-repository

I think sergey/ravenexp needs to do initiate this and drevans will need to accept it.  All watchers, etc will be moved to the splintchecker orgranization.  For some reason the invite didn't seem to work?  At least 5 hours later, I didn't see it?

**Comment by ravenexp** [comment] 2019-07-25 18:18
Ok, everything seems in order now. Github tells me the repository is owned by https://github.com/splintchecker.

Sorry for stalling this simple procedure for half a year.
Unfortunately, I don't have much time for hobby projects these days...

**Comment by evansuva** [comment] 2019-07-26 21:48
Thanks Sergey! Looks like everything is done now - much appreciate all your and @bpringlemeir's work on this.

**Closed** 2019-07-27 11:09 UTC
